#!/bin/bash

MAC="41:42:31:79:E9:F9"

if ! bluetoothctl info $MAC | grep -q "Connected: yes"; then
  bluetoothctl scan on &>/dev/null &
  SCAN_PID=$!
  sleep 1

  bluetoothctl disconnect $MAC &>/dev/null
  bluetoothctl connect $MAC &>/dev/null
  bluetoothctl trust $MAC &>/dev/null
  bluetoothctl pair $MAC &>/dev/null

  bluetoothctl scan off &>/dev/null
  wait $SCAN_PID
fi

dev=$(pactl list sinks short | awk '{print $2 }' | grep 41_42_31)
pactl set-default-sink $dev &>/dev/null
